site_name: Refuel Docs
site_url: https://refuel.ai/
repo_url: https://github.com/refuel-ai/refuel-docs
repo_name: refuel-ai/refuel-docs

nav:
  - Welcome: index.md
  - Cloud SDK: python-sdk.md
  - Autolabel:
      - Introduction: autolabel/index.md
      - Getting Started: autolabel/guide/overview/getting-started.md
      - Tutorial - Toxic comment classification: guide/overview/tutorial-classification.md
      - Models:
          - LLMs: autolabel/guide/llms/llms.md
          - Embedding Models: autolabel/guide/llms/embeddings.md
          - Benchmarks: autolabel/guide/llms/benchmarks.md
      - Labeling Tasks:
          - Classification Task: autolabel/guide/tasks/classification_task.md
          - Multilabel Classification Task: autolabel/guide/tasks/multilabel_classification_task.md
          - Entity Matching Task: autolabel/guide/tasks/entity_matching_task.md
          - Named Entity Recognition Task: autolabel/guide/tasks/named_entity_recognition_task.md
          - Question Answering Task: autolabel/guide/tasks/question_answering_task.md
      - Transformations:
          - Introduction: autolabel/guide/transforms/introduction.md
          - Webpage Transform: autolabel/guide/transforms/webpage_transform.md
          - PDF Transform: autolabel/guide/transforms/pdf_transform.md
          - Image Transform: autolabel/guide/transforms/image_transform.md
      - Improving Labeling Accuracy:
          - Prompting Better: autolabel/guide/accuracy/prompting-better.md
          - Few-shot Prompting: autolabel/guide/accuracy/few-shot.md
          - Confidence: autolabel/guide/accuracy/confidence.md
          - Chain of Thought: autolabel/guide/accuracy/chain-of-thought.md
      - Reliability and Robustness:
          - LLM Output Caching: autolabel/guide/reliability/llm-output-caching.md
          - State Management: autolabel/guide/reliability/state-management.md
      - Working with Autolabel:
          - Configs: autolabel/guide/resources/configs.md
          - AutolabelDataset: autolabel/guide/resources/autolabel_dataset.md
          - CLI: autolabel/guide/resources/CLI.md
          - Refuel-provided Datasets: autolabel/guide/resources/refuel_datasets.md
          - Synthetic Dataset Generation: autolabel/guide/resources/synthetic_dataset_generation.md
      - Reference:
          - AutoLabeler: autolabel/reference/labeler.md
          - Config: autolabel/reference/configs.md
          - Models: autolabel/reference/models.md
          - Tasks: autolabel/reference/tasks.md
          - Schema: autolabel/reference/schema.md
          - Cache: autolabel/reference/cache.md
          - Example Selector: autolabel/reference/example_select.md
          - Data Models: autolabel/reference/data_models.md

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [autolabel] # search packages in the autolabel folder
  - search
  - mkdocs-jupyter
  - table-reader

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
